
GET http://localhost:8081/api/category

###

POST http://localhost:8081/api/item
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="item"
Content-Type: application/json

{
  "name": "Beef vuna",
  "description": "Special Beef vuna",
  "price": 249.99,
  "categoryIds": [2]
}
--MyBoundary

###

### Create Addon with File
POST http://localhost:8081/api/addon
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="addon"
Content-Type: application/json

{
  "name": "Coca Cola",
  "description": "Refreshing Beverage",
  "price": 25.00,
  "itemIds": [1,5,6]
}

--WebAppBoundary

#Content-Disposition: form-data; name="file"; filename="french_fry.png"
#Content-Type: image/png
#
#< /Users/md.habiburrahman/Downloads/french_fry.png
#
#--WebAppBoundary--